# https://github.com/cypress-io/cypress-docker-images/tree/master/browsers
stages:
  - test

test_cypress:
  image: cypress/browsers:latest
  stage: test
  script:  
    - npx cypress install
    - npx cypress run -b chrome